---
apiVersion: eda.ansible.com/v1alpha1
kind: EDA
metadata:
  name: eda
spec:
  admin_user: admin
  admin_password_secret: eda-admin-password

  ingress_type: ingress
  ingress_tls_secret: eda-secret-tls
  hostname: eda.example.com

  automation_server_url: https://awx.example.com/
  automation_server_ssl_verify: no

  image: quay.io/ansible/eda-server
  image_version: sha-70529ad

  image_web: quay.io/ansible/eda-ui
  image_web_version: 2.4.716

  extra_settings:
    - setting: EDA_CSRF_TRUSTED_ORIGINS
      value: http://eda-api:8000

  api:
    replicas: 1
    resource_requirements:
      requests: {}
  ui:
    replicas: 1
    resource_requirements:
      requests: {}
  default_worker:
    replicas: 2
    resource_requirements:
      requests: {}
  activation_worker:
    replicas: 3
    resource_requirements:
      requests: {}
  redis:
    replicas: 1
    resource_requirements:
      requests: {}
  database:
    database_secret: eda-database-configuration
    postgres_storage_class: eda-postgres-volume
    storage_requirements:
      requests:
        storage: 8Gi
    resource_requirements:
      requests: {}

  # Uncomment to reveal "censored" logs
  #no_log: false
