---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulp-operator
  labels:
    app.kubernetes.io/name: pulp-operator
    app.kubernetes.io/component: operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pulp-operator
      app.kubernetes.io/component: operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pulp-operator
        app.kubernetes.io/component: operator
    spec:
      serviceAccountName: pulp-operator
      containers:
        - name: pulp-operator
          image: "quay.io/pulp/pulp-operator:0.3.0"
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - mountPath: /tmp/ansible-operator/runner
              name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "pulp-operator"
            - name: ANSIBLE_GATHERING
              value: explicit
          livenessProbe:
            httpGet:
              path: /healthz
              port: 6789
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
        - name: runner
          emptyDir: {}
